receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  jaeger:
    protocols:
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_binary:
        endpoint: 0.0.0.0:6832
      thrift_http:
        endpoint: 0.0.0.0:14268
      grpc:
        endpoint: 0.0.0.0:14250


# 在这里分别定义两个处理器的配置
processors:
  batch:
  attributesfilter:
    drop:
      - key: "service.name"
        value: "traces-demo"

exporters:
  debug:
    verbosity: normal

  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

  file:
    format: json
    path: ./traces



service:
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [batch]
      exporters: [otlp, file]