dist:
  name: collector-dev
  description: "A custom OpenTelemetry Collector build with specific receivers, processors, and exporters"
  output_path: ./
  otelcol_version: "v0.135.0" # 我们使用一个稳定版本


receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/otlpjsonfilereceiver v0.135.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor v0.135.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.135.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter v0.135.0
